name: machinavision
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  tflite: ^1.1.2
  image: ^3.1.3
  camera: ^0.9.5+1
  fl_chart: ^0.50.6
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/converted_mnist_model.tflite
    - assets/labels.txt
    - assets/mobilenet_v1_1.0_224.tflite
    - assets/mobilenet_v1_1.0_224.txt
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/yolov2_tiny.tflite
    - assets/yolov2_tiny.txt

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
